- name: install font requirements
  yum:
    name:
      - fontconfig
      - freetype*
      - urw-fonts
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: install font requirements
  apt:
    name:
      - fontconfig
      - freetype*
      - fonts-texgyre
    state: latest
  when: ansible_facts['os_family'] == "Debian"
