---
- name: deploy Grafana
  yum:
    name: grafana
    state: latest
  notify:
    - enabled grafana service
  when: ansible_facts['os_family'] == "RedHat"

- name: deploy Grafana
  apt:
    name: grafana
    state: latest
  notify:
    - enabled grafana service
  when: ansible_facts['os_family'] == "Debian"
