---
- name: start ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: start ntp service
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"

