---
- name: install base packages
  yum:
    name: "{{ base_packages }}"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: install base packages
  apt:
    name: "{{ base_packages }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
